name: version_poc
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  hooks_riverpod: ^2.4.3
  json_annotation: ^4.8.0
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  retrofit_generator: ^8.0.1

flutter:
  uses-material-design: true
